"""Simplification — file collection and diff utilities."""

from __future__ import annotations

import subprocess
from typing import TYPE_CHECKING, NamedTuple

from mantle.core import issues, project

if TYPE_CHECKING:
    from pathlib import Path


# ── Types ────────────────────────────────────────────────────────


class DiffStats(NamedTuple):
    """Aggregated diff statistics across commits.

    Attributes:
        files: Number of files changed.
        lines_added: Total lines added (insertions).
        lines_removed: Total lines removed (deletions).
        lines_changed: Sum of lines_added and lines_removed.
    """

    files: int
    lines_added: int
    lines_removed: int
    lines_changed: int


# ── Constants ────────────────────────────────────────────────────


DEFAULT_DIFF_PATHS: dict[str, tuple[str, ...]] = {
    "source": ("src/",),
    "test": ("tests/",),
}
PRIMARY_CATEGORIES: frozenset[str] = frozenset({"source", "test"})


LLM_BLOAT_CHECKLIST: str = """\
## Bloat Pattern Checklist

1. **Unnecessary abstractions** — interfaces, base classes, \
or wrapper layers that have only one implementation
2. **Defensive over-engineering** — error handling, retries, \
or fallback paths that the current requirements don't need
3. **Code duplication** — repeated logic that could be a \
single function or shared constant
4. **Unnecessary conditionals** — branches that are always \
true/false given current usage
5. **Dead code** — functions, variables, or imports that are \
never called or used
6. **Comment noise** — restating what the code already says, \
or TODO/FIXME with no actionable context
7. **Slop scaffolding** — boilerplate, config, or glue code \
generated by LLMs that adds no value
8. **Over-parameterisation** — function arguments or config \
options that are never varied in practice
"""


# ── Private helpers ──────────────────────────────────────────────


def _verify_issue_exists(project_root: Path, issue: int) -> None:
    """Raise FileNotFoundError if the issue file does not exist."""
    issue_path = issues.find_issue_path(project_root, issue)
    if issue_path is None:
        msg = f"Issue {issue} not found"
        raise FileNotFoundError(msg)
    issues.load_issue(issue_path)


def _grep_issue_commits(project_root: Path, issue: int) -> list[str]:
    """Return commit hashes for commits referencing the given issue.

    Searches for ``(issue-N)`` in commit messages, and for N < 10
    also searches ``(issue-0N)`` to catch zero-padded history.

    Args:
        project_root: Directory containing the git repo.
        issue: Issue number to search for.

    Returns:
        List of commit hashes, most-recent first, deduplicated.
    """

    def _grep(pattern: str) -> list[str]:
        result = subprocess.run(
            ["git", "log", "--oneline", f"--grep={pattern}", "--format=%H"],
            capture_output=True,
            text=True,
            check=True,
            cwd=project_root,
        )
        return result.stdout.strip().splitlines()

    commit_hashes = _grep(f"(issue-{issue})")

    if issue < 10:
        padded = _grep(f"(issue-0{issue})")
        seen = set(commit_hashes)
        commit_hashes += [h for h in padded if h not in seen]

    return commit_hashes


# ── Public API ───────────────────────────────────────────────────


def collect_issue_files(
    project_root: Path,
    issue: int,
) -> tuple[str, ...]:
    """Collect files changed by an issue's implementation.

    Loads the issue to verify it exists, then finds commits
    matching the conventional commit pattern ``feat(issue-N):``
    and collects all files changed across those commits.

    For single-digit issues (N < 10), also searches for
    zero-padded forms like ``(issue-01)`` to catch early
    project history.

    Args:
        project_root: Directory containing .mantle/.
        issue: Issue number to collect files for.

    Returns:
        Tuple of file paths relative to project root,
        or empty tuple if no matching commits exist.

    Raises:
        FileNotFoundError: If the issue file does not exist.
    """
    _verify_issue_exists(project_root, issue)
    commit_hashes = _grep_issue_commits(project_root, issue)

    if not commit_hashes:
        return ()

    first_commit = commit_hashes[-1]
    last_commit = commit_hashes[0]

    diff_result = subprocess.run(
        ["git", "diff", "--name-only", f"{first_commit}^..{last_commit}"],
        capture_output=True,
        text=True,
        check=True,
        cwd=project_root,
    )

    files = [f for f in diff_result.stdout.strip().splitlines() if f]
    return tuple(files)


def load_diff_paths(
    project_root: Path,
) -> tuple[dict[str, tuple[str, ...]], bool]:
    """Load diff_paths from .mantle/config.md or return defaults.

    When ``.mantle/config.md`` is missing, the file cannot be read, or the
    ``diff_paths`` field is absent/empty, returns
    ``(DEFAULT_DIFF_PATHS, False)``.

    Args:
        project_root: Directory containing .mantle/.

    Returns:
        Tuple of (mapping, is_custom). ``is_custom`` is True when the
        config field is present (enables the ``"other"`` bucket in
        categorised stats).
    """
    try:
        config = project.read_config(project_root)
    except FileNotFoundError:
        return DEFAULT_DIFF_PATHS, False
    raw = config.get("diff_paths")
    if not raw:
        return DEFAULT_DIFF_PATHS, False
    return {k: tuple(v) for k, v in raw.items()}, True


def collect_issue_diff_stats_categorised(
    project_root: Path,
    issue: int,
) -> dict[str, DiffStats]:
    """Per-category diff stats for an issue.

    Categories come from ``.mantle/config.md`` ``diff_paths`` frontmatter,
    or default to ``source=src/``, ``test=tests/``. When ``diff_paths``
    is explicitly configured, files matching no configured category are
    reported under an ``"other"`` key. When defaults are in use, the
    ``"other"`` key is omitted (matches legacy behaviour).

    File classification uses first-matching-prefix semantics in declared
    category order; a file matches a prefix when its path string starts
    with that prefix.

    Args:
        project_root: Directory containing .mantle/.
        issue: Issue number to collect diff stats for.

    Returns:
        Mapping from category name to DiffStats. All declared categories
        are always present (with zero stats if empty). The ``"other"``
        key appears only when ``diff_paths`` is explicitly configured.

    Raises:
        FileNotFoundError: If the issue file does not exist.
    """
    _verify_issue_exists(project_root, issue)
    paths, is_custom = load_diff_paths(project_root)
    commit_hashes = _grep_issue_commits(project_root, issue)

    categories: dict[str, DiffStats] = {
        name: DiffStats(0, 0, 0, 0) for name in paths
    }
    if is_custom:
        categories["other"] = DiffStats(0, 0, 0, 0)

    if not commit_hashes:
        return categories

    first_commit = commit_hashes[-1]
    last_commit = commit_hashes[0]

    numstat = subprocess.run(
        ["git", "diff", "--numstat", f"{first_commit}^..{last_commit}"],
        capture_output=True,
        text=True,
        check=True,
        cwd=project_root,
    )

    for line in numstat.stdout.splitlines():
        parts = line.split("\t", 2)
        if len(parts) != 3:
            continue
        added_s, removed_s, path = parts
        # Binary files show '-' for counts; treat as zero.
        added = int(added_s) if added_s.isdigit() else 0
        removed = int(removed_s) if removed_s.isdigit() else 0
        category = _classify_path(path, paths, is_custom)
        if category is None:
            continue
        prev = categories[category]
        categories[category] = DiffStats(
            files=prev.files + 1,
            lines_added=prev.lines_added + added,
            lines_removed=prev.lines_removed + removed,
            lines_changed=prev.lines_changed + added + removed,
        )

    return categories


def _classify_path(
    path: str,
    paths: dict[str, tuple[str, ...]],
    is_custom: bool,
) -> str | None:
    """Return the category a path belongs to, or None to drop it.

    First-matching-prefix in declared order. When no category matches:
    returns ``"other"`` if ``is_custom``, else None (silently dropped).
    """
    for name, prefixes in paths.items():
        if any(path.startswith(p) for p in prefixes):
            return name
    return "other" if is_custom else None


def collect_issue_diff_stats(
    project_root: Path,
    issue: int,
) -> DiffStats:
    """Aggregate diff stats for an issue, scoped to source+test categories.

    Thin wrapper over :func:`collect_issue_diff_stats_categorised` that
    sums DiffStats for the ``source`` and ``test`` categories (the
    :data:`PRIMARY_CATEGORIES` set). Matches the legacy contract used by
    ``build.md`` Step 7's simplify-skip heuristic.

    Args:
        project_root: Directory containing .mantle/.
        issue: Issue number to collect diff stats for.

    Returns:
        DiffStats summed across ``source`` and ``test`` categories, or
        ``DiffStats(0, 0, 0, 0)`` when neither category has any changes.

    Raises:
        FileNotFoundError: If the issue file does not exist.
    """
    categories = collect_issue_diff_stats_categorised(project_root, issue)
    files = lines_added = lines_removed = 0
    for name in PRIMARY_CATEGORIES:
        stats = categories.get(name)
        if stats is None:
            continue
        files += stats.files
        lines_added += stats.lines_added
        lines_removed += stats.lines_removed
    return DiffStats(
        files=files,
        lines_added=lines_added,
        lines_removed=lines_removed,
        lines_changed=lines_added + lines_removed,
    )


def collect_changed_files(
    project_root: Path,
) -> tuple[str, ...]:
    """Collect all changed files in the working tree.

    Includes staged changes, unstaged changes, and untracked
    files (excluding ignored files).

    Args:
        project_root: Directory containing the git repo.

    Returns:
        Tuple of file paths relative to project root.
    """
    diff_result = subprocess.run(
        ["git", "diff", "--name-only", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
        cwd=project_root,
    )

    untracked_result = subprocess.run(
        ["git", "ls-files", "--others", "--exclude-standard"],
        capture_output=True,
        text=True,
        check=True,
        cwd=project_root,
    )

    all_files = {
        line
        for output in (diff_result.stdout, untracked_result.stdout)
        for line in output.strip().splitlines()
        if line
    }

    return tuple(sorted(all_files))
