"""Parse Claude Code session JSONL into per-story telemetry records."""

from __future__ import annotations

import json
import os
import re
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pydantic

if TYPE_CHECKING:
    from mantle.core import stages

# ── Data models ──────────────────────────────────────────────────


class Usage(pydantic.BaseModel, frozen=True):
    """Token usage breakdown from an assistant turn.

    Attributes:
        input_tokens: Non-cached input tokens consumed.
        output_tokens: Tokens generated by the model.
        cache_read_input_tokens: Tokens served from the prompt cache.
        cache_creation_input_tokens: Tokens written into the prompt
            cache on this turn.
    """

    input_tokens: int
    output_tokens: int
    cache_read_input_tokens: int = 0
    cache_creation_input_tokens: int = 0


class Turn(pydantic.BaseModel, frozen=True):
    """A single assistant turn parsed from a Claude Code JSONL.

    Attributes:
        uuid: Turn identifier within the session.
        parent_uuid: Parent turn uuid, or None for session root.
        session_id: Claude Code session identifier.
        timestamp: Wall-clock timestamp recorded on the turn.
        model: Model id that produced the turn, if present.
        is_sidechain: True for subagent (Agent-spawned) turns.
        usage: Token usage block, if present.
    """

    uuid: str
    parent_uuid: str | None
    session_id: str
    timestamp: datetime
    model: str | None
    is_sidechain: bool
    usage: Usage | None


class SubagentMeta(pydantic.BaseModel, frozen=True):
    """Parsed `agent-*.meta.json` sidecar.

    Claude Code owns this schema; use `extra='ignore'` so new fields
    upstream never break parsing.

    Attributes:
        agent_type: The type of agent that ran this sub-session
            (e.g. 'story-implementer', 'refactorer', 'general-purpose').
        description: Free-text description supplied at Agent-tool spawn
            time. Build telemetry parses ``story <N>`` out of this to
            attribute runs to a story.
    """

    model_config = pydantic.ConfigDict(extra="ignore")

    agent_type: str = pydantic.Field(alias="agentType")
    description: str | None = None


class StoryRun(pydantic.BaseModel, frozen=True):
    """Aggregated telemetry for one sidechain cluster (agent run).

    Attributes:
        story_id: Story number this run corresponds to, or None when
            no marker could be matched.
        model: Most frequent model id observed across the cluster.
        started: Earliest turn timestamp in the cluster.
        finished: Latest turn timestamp in the cluster.
        duration_s: Wall-clock duration in seconds.
        usage: Summed token usage across the cluster.
        turn_count: Number of sidechain turns in the cluster.
        stage: Stage name attributed to this run, or None when unknown.
        cost_usd: Dollar cost in USD computed at build-finish time from
            the prices in ``cost-policy.md``. ``None`` when prices were
            unavailable or the model could not be resolved.
    """

    story_id: int | None
    model: str
    started: datetime
    finished: datetime
    duration_s: float
    usage: Usage
    turn_count: int
    stage: str | None = None
    cost_usd: float | None = None


class BuildReport(pydantic.BaseModel, frozen=True):
    """Summarised build over one Claude Code session.

    Attributes:
        session_id: Claude Code session identifier.
        started: Earliest assistant turn timestamp.
        finished: Latest assistant turn timestamp.
        stories: Aggregated story runs for this session.
    """

    session_id: str
    started: datetime
    finished: datetime
    stories: tuple[StoryRun, ...]


# ── Constants ────────────────────────────────────────────────────

_AGENT_TYPE_TO_STAGE: dict[str, str] = {
    "story-implementer": "implement",
    "refactorer": "simplify",
    "general-purpose": "verify",
}

_STORY_ID_RE = re.compile(r"\bstory\s+(\d+)\b", re.IGNORECASE)


def _parse_story_id(description: str | None) -> int | None:
    """Extract a story number from an Agent-tool description.

    Matches the first ``story <N>`` substring (case-insensitive).
    Real meta sidecars use descriptions like ``"Implement story 2"``
    or ``"Implement issue 74 story 1"`` — the regex picks up the
    story number while ignoring the issue number.
    """
    if not description:
        return None
    match = _STORY_ID_RE.search(description)
    return int(match.group(1)) if match else None


# ── Public API ───────────────────────────────────────────────────


def find_session_file(
    session_id: str,
    projects_root: Path | None = None,
) -> Path:
    """Locate the JSONL transcript for a Claude Code session.

    Resolution order:
      1. ``projects_root`` argument if supplied.
      2. ``CLAUDE_PROJECTS_DIR`` environment variable.
      3. ``~/.claude/projects``.

    Args:
        session_id: Claude Code session uuid (filename stem).
        projects_root: Optional override for the projects directory.

    Returns:
        Absolute path to ``<projects_root>/<slug>/<session_id>.jsonl``.

    Raises:
        FileNotFoundError: If no matching session file exists.
    """
    root = _resolve_projects_root(projects_root)

    if root.is_dir():
        matches = list(root.glob(f"*/{session_id}.jsonl"))
        if matches:
            return matches[0]

    msg = f"Session file for session_id={session_id!r} not found under {root}."
    raise FileNotFoundError(msg)


def find_subagent_files(
    parent_session_id: str,
    projects_root: Path | None = None,
) -> tuple[Path, ...]:
    """Locate sub-agent JSONLs for a parent Claude Code session.

    Resolution order matches `find_session_file`: `projects_root`
    arg → `CLAUDE_PROJECTS_DIR` env → `~/.claude/projects`. Sub-agent
    transcripts live at
    `<projects_root>/<slug>/<parent_session_id>/subagents/agent-*.jsonl`.

    Returns tuple sorted by the file's first-turn timestamp so the
    caller sees chronologically ordered runs. Empty tuple when the
    `subagents/` directory is absent (common for older sessions
    predating the split file layout).

    Args:
        parent_session_id: Claude Code session uuid of the parent session.
        projects_root: Optional override for the projects directory.

    Returns:
        Tuple of paths to sub-agent JSONL files, sorted by first-turn
        timestamp ascending.
    """
    root = _resolve_projects_root(projects_root)
    pattern = f"*/{parent_session_id}/subagents/agent-*.jsonl"
    paths = list(root.glob(pattern))
    if not paths:
        return ()

    def _first_turn_ts(path: Path) -> float:
        turns = read_subagent(path)
        return turns[0].timestamp.timestamp() if turns else path.stat().st_mtime

    return tuple(sorted(paths, key=_first_turn_ts))


def read_session(session_file: Path) -> tuple[Turn, ...]:
    """Parse a Claude Code JSONL file into assistant turns.

    Iterates the file line-by-line, returning only records with
    ``type == "assistant"``. Malformed lines (partial writes,
    invalid JSON) are skipped silently so that reports are still
    producible for in-flight sessions.

    Args:
        session_file: Path to the ``.jsonl`` transcript file.

    Returns:
        Tuple of parsed assistant turns in file order.
    """
    turns: list[Turn] = []
    with session_file.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            turn = _parse_assistant_line(line)
            if turn is not None:
                turns.append(turn)
    return tuple(turns)


def read_subagent(jsonl_path: Path) -> tuple[Turn, ...]:
    """Parse a sub-agent JSONL into assistant turns.

    Sub-agent files use the same record shape as parent sessions —
    one assistant turn per line, with `isSidechain: true` already
    set. Reuses the parent-session parser.

    Args:
        jsonl_path: Path to the sub-agent ``.jsonl`` transcript file.

    Returns:
        Tuple of parsed assistant turns in file order.
    """
    return read_session(jsonl_path)


def read_meta(jsonl_path: Path) -> SubagentMeta | None:
    """Parse the sibling `agent-*.meta.json` sidecar.

    Given `<dir>/agent-<id>.jsonl`, reads `<dir>/agent-<id>.meta.json`.
    Returns None when the sidecar is absent or malformed — callers
    degrade gracefully to `stage=None`.

    Args:
        jsonl_path: Path to the sub-agent ``.jsonl`` transcript file.

    Returns:
        Parsed SubagentMeta, or None when the sidecar is absent or
        malformed.
    """
    meta_path = jsonl_path.with_name(jsonl_path.stem + ".meta.json")
    try:
        data = json.loads(meta_path.read_text(encoding="utf-8"))
        return SubagentMeta.model_validate(data)
    except (
        FileNotFoundError,
        json.JSONDecodeError,
        pydantic.ValidationError,
        OSError,
    ):
        return None


def group_stories(
    parent_turns: tuple[Turn, ...] = (),
    subagent_paths: tuple[Path, ...] = (),
    stage_windows: tuple[stages.StageWindow, ...] = (),
) -> tuple[StoryRun, ...]:
    """Produce per-stage `StoryRun` records from three sources.

    - One run per sub-agent JSONL path, stage attributed via the
      sidecar's `agentType` through `_AGENT_TYPE_TO_STAGE`. Unknown
      types yield `stage=None`.
    - One run per `StageWindow` that overlaps any parent turn; the
      run aggregates all parent turns with timestamp inside the
      half-open `[start, end)` interval.
    - Results sorted ascending by `started`.

    Args:
        parent_turns: Parsed turns from the parent session JSONL.
        subagent_paths: Paths to sub-agent JSONL files to parse.
        stage_windows: Half-open stage windows from `stages.windows_for_session`.

    Returns:
        Tuple of aggregated `StoryRun` records, one per sub-agent or
        occupied stage window, sorted ascending by `started`.
    """
    runs: list[StoryRun] = []

    for path in subagent_paths:
        turns = read_subagent(path)
        if not turns:
            continue
        meta = read_meta(path)
        agent_type = meta.agent_type if meta else None
        stage = _AGENT_TYPE_TO_STAGE.get(agent_type) if agent_type else None
        story_id = _parse_story_id(meta.description if meta else None)
        run = _aggregate_cluster(list(turns))
        runs.append(
            run.model_copy(update={"stage": stage, "story_id": story_id})
        )

    for window in stage_windows:
        window_turns = [
            t for t in parent_turns if window.start <= t.timestamp < window.end
        ]
        if not window_turns:
            continue
        run = _aggregate_cluster(window_turns)
        runs.append(run.model_copy(update={"stage": window.stage}))

    runs.sort(key=lambda r: r.started)
    return tuple(runs)


def summarise(
    session_id: str,
    turns: tuple[Turn, ...],
    story_runs: tuple[StoryRun, ...],
) -> BuildReport:
    """Build a top-level report from parsed turns and story runs.

    Wall-clock bounds are derived from the outer timestamps of all
    parsed turns. For empty sessions, both bounds are set to
    ``datetime.min``.

    Args:
        session_id: Claude Code session identifier.
        turns: Parsed session turns.
        story_runs: Aggregated per-story records.

    Returns:
        A ``BuildReport`` combining bounds and story runs.
    """
    if turns:
        timestamps = [t.timestamp for t in turns]
        started = min(timestamps)
        finished = max(timestamps)
    else:
        started = finished = datetime.min

    return BuildReport(
        session_id=session_id,
        started=started,
        finished=finished,
        stories=story_runs,
    )


def current_session_id(project_dir: Path | None = None) -> str:
    """Return the Claude Code session id.

    Looks first at the ``CLAUDE_SESSION_ID`` environment variable.
    Falls back to ``<project_dir>/.mantle/.session-id``, which the
    Mantle SessionStart hook writes from the hook payload.

    Args:
        project_dir: Project directory to search for the fallback
            file. Defaults to cwd.

    Returns:
        The Claude Code session id.

    Raises:
        RuntimeError: If neither source yields an id — typically
            means we are running outside a Claude Code session.
    """
    value = os.environ.get("CLAUDE_SESSION_ID")
    if value:
        return value

    if project_dir is None:
        project_dir = Path.cwd()
    fallback = project_dir / ".mantle" / ".session-id"
    if fallback.is_file():
        content = fallback.read_text(encoding="utf-8").strip()
        if content:
            return content

    msg = (
        "CLAUDE_SESSION_ID is not set and no .mantle/.session-id "
        "fallback file exists. This command expects to run inside "
        "a Claude Code session."
    )
    raise RuntimeError(msg)


def render_report(
    report: BuildReport,
    issue: int,
) -> str:
    """Render a build report as YAML frontmatter plus summary markdown.

    The output is a complete build-file body: a YAML frontmatter
    block with issue, timestamps, session id, and a ``stories`` list
    followed by a ``## Summary`` section with story runs grouped by
    stage. Empty reports (no story runs detected) still produce valid
    frontmatter and a placeholder summary line.

    Args:
        report: Aggregated build report.
        issue: Issue number this build corresponds to.

    Returns:
        Full build file body as a string ending in a newline.
    """
    lines: list[str] = ["---"]
    lines.append(f"issue: {issue}")
    lines.append(f"session_id: {report.session_id}")
    lines.append(f"started: {report.started.isoformat()}")
    lines.append(f"finished: {report.finished.isoformat()}")
    lines.append("stories:")
    for story in report.stories:
        story_id = "null" if story.story_id is None else str(story.story_id)
        stage_val = "null" if story.stage is None else story.stage
        lines.append(f"  - story_id: {story_id}")
        lines.append(f"    stage: {stage_val}")
        lines.append(f"    model: {story.model}")
        lines.append(f"    started: {story.started.isoformat()}")
        lines.append(f"    finished: {story.finished.isoformat()}")
        lines.append(f"    duration_s: {story.duration_s:.1f}")
        lines.append(f"    turn_count: {story.turn_count}")
        lines.append(f"    input_tokens: {story.usage.input_tokens}")
        lines.append(f"    output_tokens: {story.usage.output_tokens}")
        lines.append(
            f"    cache_read_input_tokens: "
            f"{story.usage.cache_read_input_tokens}"
        )
        lines.append(
            f"    cache_creation_input_tokens: "
            f"{story.usage.cache_creation_input_tokens}"
        )
        if story.cost_usd is not None:
            lines.append(f"    cost_usd: {story.cost_usd:.4f}")
    lines.append("---")
    lines.append("")
    lines.append("## Summary")
    lines.append("")

    if not report.stories:
        lines.append("No story runs detected in this build.")
        lines.append("")
        return "\n".join(lines)

    # Group by stage: known stages first in order of appearance, then Unattributed
    stage_order: list[str] = []
    by_stage: dict[str, list[StoryRun]] = {}
    unattributed: list[StoryRun] = []

    for story in report.stories:
        if story.stage is None:
            unattributed.append(story)
        else:
            if story.stage not in by_stage:
                stage_order.append(story.stage)
                by_stage[story.stage] = []
            by_stage[story.stage].append(story)

    has_costs = any(s.cost_usd is not None for s in report.stories)

    def _render_table(stories: list[StoryRun]) -> None:
        if has_costs:
            lines.append(
                "| Story | Model | Duration (s) | Turns | In tok | Out tok |"
                " Cost ($) |"
            )
            lines.append(
                "|-------|-------|--------------|-------|--------|---------|"
                "----------|"
            )
        else:
            lines.append(
                "| Story | Model | Duration (s) | Turns | In tok | Out tok |"
            )
            lines.append(
                "|-------|-------|--------------|-------|--------|---------|"
            )
        for story in stories:
            story_label = "—" if story.story_id is None else str(story.story_id)
            row = (
                f"| {story_label} | {story.model} | "
                f"{story.duration_s:.1f} | {story.turn_count} | "
                f"{story.usage.input_tokens} | {story.usage.output_tokens} |"
            )
            if has_costs:
                cost_cell = (
                    "—"
                    if story.cost_usd is None
                    else f"{story.cost_usd:.4f}"
                )
                row += f" {cost_cell} |"
            lines.append(row)

    for stage in stage_order:
        lines.append(f"### {stage}")
        lines.append("")
        _render_table(by_stage[stage])
        lines.append("")

    if unattributed:
        lines.append("### Unattributed")
        lines.append("")
        _render_table(unattributed)
        lines.append("")

    return "\n".join(lines)


# ── Internal helpers ─────────────────────────────────────────────


def _resolve_projects_root(projects_root: Path | None) -> Path:
    """Resolve the Claude Code projects directory.

    Args:
        projects_root: Explicit override, or None.

    Returns:
        The projects root path.
    """
    if projects_root is not None:
        return projects_root

    env_root = os.environ.get("CLAUDE_PROJECTS_DIR")
    if env_root:
        return Path(env_root)

    return Path.home() / ".claude" / "projects"


def _parse_assistant_line(line: str) -> Turn | None:
    """Parse one JSONL line into a Turn, or None if malformed.

    Args:
        line: Single JSONL record text (no trailing newline).

    Returns:
        Parsed Turn, or None if the record is not an assistant turn
        or cannot be parsed.
    """
    try:
        record = json.loads(line)
    except json.JSONDecodeError, ValueError:
        return None

    if not isinstance(record, dict):
        return None
    if record.get("type") != "assistant":
        return None

    try:
        message = record.get("message") or {}
        usage_data = message.get("usage")
        usage = _parse_usage(usage_data) if usage_data else None

        return Turn(
            uuid=record["uuid"],
            parent_uuid=record.get("parentUuid"),
            session_id=record["sessionId"],
            timestamp=_parse_timestamp(record["timestamp"]),
            model=message.get("model"),
            is_sidechain=bool(record.get("isSidechain", False)),
            usage=usage,
        )
    except KeyError, ValueError, TypeError, pydantic.ValidationError:
        return None


def _parse_usage(data: dict[str, Any]) -> Usage | None:
    """Extract a Usage from a raw ``message.usage`` dict.

    Args:
        data: Raw usage dict from JSONL.

    Returns:
        Parsed Usage, or None if fields are missing/invalid.
    """
    try:
        return Usage(
            input_tokens=int(data.get("input_tokens", 0)),
            output_tokens=int(data.get("output_tokens", 0)),
            cache_read_input_tokens=int(data.get("cache_read_input_tokens", 0)),
            cache_creation_input_tokens=int(
                data.get("cache_creation_input_tokens", 0)
            ),
        )
    except TypeError, ValueError, pydantic.ValidationError:
        return None


def _parse_timestamp(raw: str) -> datetime:
    """Parse an ISO-8601 timestamp, accepting trailing ``Z``.

    Args:
        raw: Timestamp string.

    Returns:
        Parsed datetime.
    """
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    return datetime.fromisoformat(raw)


def _aggregate_cluster(cluster: list[Turn]) -> StoryRun:
    """Collapse a sidechain cluster into a single StoryRun.

    Args:
        cluster: Non-empty list of sidechain turns.

    Returns:
        Aggregated StoryRun with summed usage and modal model.
    """
    timestamps = [t.timestamp for t in cluster]
    started = min(timestamps)
    finished = max(timestamps)

    usages = [t.usage for t in cluster if t.usage is not None]
    usage = Usage(
        input_tokens=sum(u.input_tokens for u in usages),
        output_tokens=sum(u.output_tokens for u in usages),
        cache_read_input_tokens=sum(u.cache_read_input_tokens for u in usages),
        cache_creation_input_tokens=sum(
            u.cache_creation_input_tokens for u in usages
        ),
    )

    models = [t.model for t in cluster if t.model is not None]
    model = Counter(models).most_common(1)[0][0] if models else ""

    return StoryRun(
        story_id=None,
        model=model,
        started=started,
        finished=finished,
        duration_s=(finished - started).total_seconds(),
        usage=usage,
        turn_count=len(cluster),
    )
