"""Parse Claude Code session JSONL into per-story telemetry records."""

from __future__ import annotations

import json
import os
import warnings
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any

import pydantic

# ── Data models ──────────────────────────────────────────────────


class Usage(pydantic.BaseModel, frozen=True):
    """Token usage breakdown from an assistant turn.

    Attributes:
        input_tokens: Non-cached input tokens consumed.
        output_tokens: Tokens generated by the model.
        cache_read_input_tokens: Tokens served from the prompt cache.
        cache_creation_input_tokens: Tokens written into the prompt
            cache on this turn.
    """

    input_tokens: int
    output_tokens: int
    cache_read_input_tokens: int = 0
    cache_creation_input_tokens: int = 0


class Turn(pydantic.BaseModel, frozen=True):
    """A single assistant turn parsed from a Claude Code JSONL.

    Attributes:
        uuid: Turn identifier within the session.
        parent_uuid: Parent turn uuid, or None for session root.
        session_id: Claude Code session identifier.
        timestamp: Wall-clock timestamp recorded on the turn.
        model: Model id that produced the turn, if present.
        is_sidechain: True for subagent (Agent-spawned) turns.
        usage: Token usage block, if present.
    """

    uuid: str
    parent_uuid: str | None
    session_id: str
    timestamp: datetime
    model: str | None
    is_sidechain: bool
    usage: Usage | None


class Marker(pydantic.BaseModel, frozen=True):
    """Orchestrator-supplied signal mapping a story id to a timestamp.

    Attributes:
        story_id: Story number this marker refers to.
        timestamp: Wall-clock timestamp of the marker event.
    """

    story_id: int
    timestamp: datetime


class StoryRun(pydantic.BaseModel, frozen=True):
    """Aggregated telemetry for one sidechain cluster (agent run).

    Attributes:
        story_id: Story number this run corresponds to, or None when
            no marker could be matched.
        model: Most frequent model id observed across the cluster.
        started: Earliest turn timestamp in the cluster.
        finished: Latest turn timestamp in the cluster.
        duration_s: Wall-clock duration in seconds.
        usage: Summed token usage across the cluster.
        turn_count: Number of sidechain turns in the cluster.
    """

    story_id: int | None
    model: str
    started: datetime
    finished: datetime
    duration_s: float
    usage: Usage
    turn_count: int


class BuildReport(pydantic.BaseModel, frozen=True):
    """Summarised build over one Claude Code session.

    Attributes:
        session_id: Claude Code session identifier.
        started: Earliest assistant turn timestamp.
        finished: Latest assistant turn timestamp.
        stories: Aggregated story runs for this session.
    """

    session_id: str
    started: datetime
    finished: datetime
    stories: tuple[StoryRun, ...]


# ── Warnings ─────────────────────────────────────────────────────


class MarkerWindowWarning(UserWarning):
    """Issued when no marker is within the correlation window."""


# ── Constants ────────────────────────────────────────────────────

MARKER_WINDOW_SECONDS: float = 60.0


# ── Public API ───────────────────────────────────────────────────


def find_session_file(
    session_id: str,
    projects_root: Path | None = None,
) -> Path:
    """Locate the JSONL transcript for a Claude Code session.

    Resolution order:
      1. ``projects_root`` argument if supplied.
      2. ``CLAUDE_PROJECTS_DIR`` environment variable.
      3. ``~/.claude/projects``.

    Args:
        session_id: Claude Code session uuid (filename stem).
        projects_root: Optional override for the projects directory.

    Returns:
        Absolute path to ``<projects_root>/<slug>/<session_id>.jsonl``.

    Raises:
        FileNotFoundError: If no matching session file exists.
    """
    root = _resolve_projects_root(projects_root)

    if root.is_dir():
        matches = list(root.glob(f"*/{session_id}.jsonl"))
        if matches:
            return matches[0]

    msg = f"Session file for session_id={session_id!r} not found under {root}."
    raise FileNotFoundError(msg)


def read_session(session_file: Path) -> tuple[Turn, ...]:
    """Parse a Claude Code JSONL file into assistant turns.

    Iterates the file line-by-line, returning only records with
    ``type == "assistant"``. Malformed lines (partial writes,
    invalid JSON) are skipped silently so that reports are still
    producible for in-flight sessions.

    Args:
        session_file: Path to the ``.jsonl`` transcript file.

    Returns:
        Tuple of parsed assistant turns in file order.
    """
    turns: list[Turn] = []
    with session_file.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            turn = _parse_assistant_line(line)
            if turn is not None:
                turns.append(turn)
    return tuple(turns)


def group_stories(
    turns: tuple[Turn, ...],
    markers: tuple[Marker, ...] = (),
) -> tuple[StoryRun, ...]:
    """Cluster sidechain turns into per-story runs.

    A new cluster starts when a sidechain turn's ``parent_uuid`` is
    not in the current cluster's uuid set (i.e. a fresh Agent
    spawn). Non-sidechain turns are ignored. When ``markers`` are
    supplied, each cluster is assigned the story id of the nearest
    preceding marker within ``MARKER_WINDOW_SECONDS``. Clusters
    that fall outside the window retain ``story_id=None`` and emit
    a ``MarkerWindowWarning``.

    Args:
        turns: Parsed session turns in chronological order.
        markers: Orchestrator-supplied story id timestamps.

    Returns:
        Tuple of aggregated ``StoryRun`` records, one per cluster.
    """
    clusters: list[list[Turn]] = []
    current_uuids: set[str] = set()

    for turn in turns:
        if not turn.is_sidechain:
            continue
        if clusters and turn.parent_uuid in current_uuids:
            clusters[-1].append(turn)
            current_uuids.add(turn.uuid)
        else:
            clusters.append([turn])
            current_uuids = {turn.uuid}

    runs = [_aggregate_cluster(cluster) for cluster in clusters]
    return _attach_story_ids(tuple(runs), markers)


def summarise(
    session_id: str,
    turns: tuple[Turn, ...],
    story_runs: tuple[StoryRun, ...],
) -> BuildReport:
    """Build a top-level report from parsed turns and story runs.

    Wall-clock bounds are derived from the outer timestamps of all
    parsed turns. For empty sessions, both bounds are set to
    ``datetime.min``.

    Args:
        session_id: Claude Code session identifier.
        turns: Parsed session turns.
        story_runs: Aggregated per-story records.

    Returns:
        A ``BuildReport`` combining bounds and story runs.
    """
    if turns:
        timestamps = [t.timestamp for t in turns]
        started = min(timestamps)
        finished = max(timestamps)
    else:
        started = finished = datetime.min

    return BuildReport(
        session_id=session_id,
        started=started,
        finished=finished,
        stories=story_runs,
    )


# ── Internal helpers ─────────────────────────────────────────────


def _resolve_projects_root(projects_root: Path | None) -> Path:
    """Resolve the Claude Code projects directory.

    Args:
        projects_root: Explicit override, or None.

    Returns:
        The projects root path.
    """
    if projects_root is not None:
        return projects_root

    env_root = os.environ.get("CLAUDE_PROJECTS_DIR")
    if env_root:
        return Path(env_root)

    return Path.home() / ".claude" / "projects"


def _parse_assistant_line(line: str) -> Turn | None:
    """Parse one JSONL line into a Turn, or None if malformed.

    Args:
        line: Single JSONL record text (no trailing newline).

    Returns:
        Parsed Turn, or None if the record is not an assistant turn
        or cannot be parsed.
    """
    try:
        record = json.loads(line)
    except json.JSONDecodeError, ValueError:
        return None

    if not isinstance(record, dict):
        return None
    if record.get("type") != "assistant":
        return None

    try:
        message = record.get("message") or {}
        usage_data = message.get("usage")
        usage = _parse_usage(usage_data) if usage_data else None

        return Turn(
            uuid=record["uuid"],
            parent_uuid=record.get("parentUuid"),
            session_id=record["sessionId"],
            timestamp=_parse_timestamp(record["timestamp"]),
            model=message.get("model"),
            is_sidechain=bool(record.get("isSidechain", False)),
            usage=usage,
        )
    except KeyError, ValueError, TypeError, pydantic.ValidationError:
        return None


def _parse_usage(data: dict[str, Any]) -> Usage | None:
    """Extract a Usage from a raw ``message.usage`` dict.

    Args:
        data: Raw usage dict from JSONL.

    Returns:
        Parsed Usage, or None if fields are missing/invalid.
    """
    try:
        return Usage(
            input_tokens=int(data.get("input_tokens", 0)),
            output_tokens=int(data.get("output_tokens", 0)),
            cache_read_input_tokens=int(data.get("cache_read_input_tokens", 0)),
            cache_creation_input_tokens=int(
                data.get("cache_creation_input_tokens", 0)
            ),
        )
    except TypeError, ValueError, pydantic.ValidationError:
        return None


def _parse_timestamp(raw: str) -> datetime:
    """Parse an ISO-8601 timestamp, accepting trailing ``Z``.

    Args:
        raw: Timestamp string.

    Returns:
        Parsed datetime.
    """
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    return datetime.fromisoformat(raw)


def _aggregate_cluster(cluster: list[Turn]) -> StoryRun:
    """Collapse a sidechain cluster into a single StoryRun.

    Args:
        cluster: Non-empty list of sidechain turns.

    Returns:
        Aggregated StoryRun with summed usage and modal model.
    """
    timestamps = [t.timestamp for t in cluster]
    started = min(timestamps)
    finished = max(timestamps)

    input_tokens = 0
    output_tokens = 0
    cache_read = 0
    cache_creation = 0
    for turn in cluster:
        if turn.usage is None:
            continue
        input_tokens += turn.usage.input_tokens
        output_tokens += turn.usage.output_tokens
        cache_read += turn.usage.cache_read_input_tokens
        cache_creation += turn.usage.cache_creation_input_tokens

    usage = Usage(
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        cache_read_input_tokens=cache_read,
        cache_creation_input_tokens=cache_creation,
    )

    models = [t.model for t in cluster if t.model is not None]
    model = Counter(models).most_common(1)[0][0] if models else ""

    return StoryRun(
        story_id=None,
        model=model,
        started=started,
        finished=finished,
        duration_s=(finished - started).total_seconds(),
        usage=usage,
        turn_count=len(cluster),
    )


def _attach_story_ids(
    runs: tuple[StoryRun, ...],
    markers: tuple[Marker, ...],
) -> tuple[StoryRun, ...]:
    """Assign story ids to runs via nearest preceding marker.

    Args:
        runs: Aggregated story runs in chronological order.
        markers: Orchestrator markers in any order.

    Returns:
        Tuple of runs with ``story_id`` populated where a marker
        lies within ``MARKER_WINDOW_SECONDS`` preceding the cluster
        start. Runs outside the window remain ``story_id=None`` and
        emit a ``MarkerWindowWarning``.
    """
    if not markers:
        return runs

    sorted_markers = sorted(markers, key=lambda m: m.timestamp)
    updated: list[StoryRun] = []

    for run in runs:
        best: Marker | None = None
        best_delta: float | None = None
        for marker in sorted_markers:
            delta = (run.started - marker.timestamp).total_seconds()
            if delta < 0:
                continue
            if best_delta is None or delta < best_delta:
                best = marker
                best_delta = delta

        if (
            best is not None
            and best_delta is not None
            and (best_delta <= MARKER_WINDOW_SECONDS)
        ):
            updated.append(run.model_copy(update={"story_id": best.story_id}))
        else:
            warnings.warn(
                (
                    "No marker within "
                    f"{MARKER_WINDOW_SECONDS:.0f}s of cluster "
                    f"starting at {run.started.isoformat()}; "
                    "story_id left unset."
                ),
                MarkerWindowWarning,
                stacklevel=2,
            )
            updated.append(run)

    return tuple(updated)
